[workspace]
members = [ "athort_common", "athort_csv",
    "athort_json"
, "athort_parquet"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Yasu"]
license = "Apache 2.0"
version = "0.1.0"
description = "Assortment of Parquet and other items"

[workspace.dependencies]
arrow = { version = "56.2.0" }
parquet = { version = "56.2.0" }
